### ISSUE TITLE
Відсутня локалізація

### ISSUE THREAD

**Issue by Krikatiny** [Gristonqqq/practice_teamwork#7]
Коли запускаю .exe, то нічого не розумію. Додайте локалізацію, пжпжпжп
![image](https://github.com/Gristonqqq/practice_teamwork/assets/120288876/92e9f0c1-fa8e-4846-aa90-c5fa084bd813)

**Comment by Gristonqqq** [comment]
Я попрацював над вашим питанням і вирішив цю проблему

**Comment by Krikatiny** [comment]
Добре, зараз перевірю

**Comment by Krikatiny** [comment]
Справді, працює
ДЯКУЮ! Буду користуватися додатком та розповім усім знайомим!
