### ISSUE TITLE
Помилка в інтерфейсі

### ISSUE THREAD

**Issue by Krikatiny** [Gristonqqq/practice_teamwork#8]
Відсутній пункт 4((((
![image](https://github.com/Gristonqqq/practice_teamwork/assets/120288876/db13b7c6-560a-4cee-b985-a3099bf37a0d)

**Comment by Gristonqqq** [comment]
Тому що не потрібно чіпати не готовий продукт

**Comment by Krikatiny** [comment]
То як? Виправите?

**Comment by Gristonqqq** [comment]
В версіях наближених до релізних все буде нормально
